runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static

- url: /.*
  script: auto

env_variables:
  EXPLORER_PW: Snowfrog1!

beta_settings:
  cloud_sql_instances: wishlist-django-348014:us-central1:wishlist-db     